#SPDX-License-Identifier: MIT-0
---
- name: Ensure ~/.ssh exists
  ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.ssh"
      state: directory
      mode: "0700"

- name: Copy SSH private key
  ansible.builtin.copy:
    src: files/id_ed25519
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    mode: "0600"

- name: Copy SSH public key
  ansible.builtin.copy:
    src: files/id_ed25519.pub
    dest: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    mode: "0644"

- name: Ensure local public key exists on control node
  ansible.builtin.stat:
    path: "{{ local_pubkey_path | expanduser }}"
  register: pubkey_stat
  delegate_to: localhost
  run_once: true


- name: Fail if local public key is missing
  ansible.builtin.fail:
    msg: "Public key not found at {{ local_pubkey_path }} on the control machine."
  when: not pubkey_stat.stat.exists
  delegate_to: localhost
  run_once: true

## Change below to password auth
- name: Ensure SSH user exists 
  ansible.builtin.user:
    name: "{{ ansible_user | default(ssh_user) }}"
    shell: /bin/bash
    groups: "{{ ssh_user_groups }}"
    append: true
    create_home: true

- name: Install SSH public key for user (like ssh-copy-id)
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    manage_dir: true
    key: "{{ lookup('file', local_pubkey_path | expanduser) }}"

- name: Optionally disable SSH password authentication
  ansible.builtin.lineinfile:
    path: "{{ sshd_config_path }}"
    regexp: '^#?PasswordAuthentication\s+'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
  when: disable_password_login
  notify: Restart SSH service

- name: Optionally disable root login over SSH
  become: true
  ansible.builtin.lineinfile:
    path: "{{ sshd_config_path }}"
    regexp: '^#?PermitRootLogin\s+'
    line: 'PermitRootLogin no'
    state: present
    backup: yes
  when: disable_root_ssh
  notify: Restart SSH service

- name: Ensure PubkeyAuthentication is enabled
  become: true
  ansible.builtin.lineinfile:
    path: "{{ sshd_config_path }}"
    regexp: '^#?PubkeyAuthentication\s+'
    line: 'PubkeyAuthentication yes'
    state: present
    backup: yes

- name: Reboot the Pi and wait for SSH
  ansible.builtin.reboot:
    reboot_timeout: 300        
    connect_timeout: 10
    post_reboot_delay: 5       
    pre_reboot_delay: 3        
    msg: "Ansible-triggered reboot"
    test_command: "whoami"
  become: true
